#!/bin/bash

GCC=/home/bklippenstein/sat/bin/arm-none-eabi-gcc

GCC_FLAGS=" -nostdinc -O0 -ffunction-sections -fdata-sections -Wall -c -fmessage-length=0 -MMD -mcpu=cortex-m0 -mthumb -mfloat-abi=soft -g3 -gdwarf-2 -gstrict-dwarf"

GCC_INCLUDE_DIRECTORIES=" -I./source -I./include -I./freescale_source -I./freescale_include"

LINKER_INCLUDE_DIRECTORIES="./freescale_arm"

LINKER_FLAGS=" -nostartfiles -nodefaultlibs -nostdlib -Xlinker --gc-sections"

LINKER_FLAGS1=" -Xlinker --undefined=__pformatter_ -Xlinker --defsym=__pformatter=__pformatter_ -Xlinker --start-group -Xlinker -lc -lm -lgcc -Xlinker --end-group -Wl,-Map,output/neon.map -n -mcpu=cortex-m0 -mthumb -mfloat-abi=soft -g3 -gdwarf-2 -gstrict-dwarf"

#Compile Source Files
echo "Compiling source files..."

if [ ! -d "./output" ]; then
    mkdir ./output
fi

if [ ! -d "./source/output" ]; then
    mkdir ./source/output
fi

if [ ! -d "./freescale_source/output" ]; then
    mkdir ./freescale_source/output
fi

$GCC ./source/MCUinit.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./source/output/MCUinit.o
$GCC ./source/main.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./source/output/main.o
$GCC ./source/__arm_end.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./source/output/__arm_end.o
$GCC ./source/__arm_start.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./source/output/__arm_start.o
$GCC ./freescale_source/__arm_eabi_init.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./freescale_source/output/__arm_eabi_init.o
$GCC ./freescale_source/gcc_ctor_dtor.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./freescale_source/output/gcc_ctor_dtor.o
$GCC ./freescale_source/ROMCopy.c $GCC_FLAGS $GCC_INCLUDE_DIRECTORIES -o ./freescale_source/output/ROMCopy.o
echo "Done compiling"

echo "Linking sources into output .elf file..."
#Link into .elf file
$GCC ./source/output/MCUinit.o ./source/output/main.o ./source/output/__arm_end.o ./source/output/__arm_start.o ./freescale_source/output/__arm_eabi_init.o ./freescale_source/output/gcc_ctor_dtor.o ./freescale_source/output/ROMCopy.o -Tsource/MKL25Z128_flash.ld $LINKER_FLAGS -L $LINKER_INCLUDE_DIRECTORIES $LINKER_FLAGS1 -o ./output/neon.elf
echo "Done Linking"
echo "Success!"
